spring.application.name=jobhunter

#config database
###
spring.jpa.hibernate.ddl-auto=update
# 1. URL k?t n?i: postgresql://host:port/database_name
spring.datasource.url=jdbc:postgresql://localhost:5432/JobHunter
# 2. Tên ng??i dùng database
spring.datasource.username=postgres
spring.datasource.password=01012005
# 4. Driver class name (PostgreSQL)

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
###


###
#config JWWT
tuan.jwt.base64-secret=vUaY3jqFbEFfltCOprX10F9bKc+tY3HJsqYzF4tfuguIf4M3jjnL5va/DeTyb64WDC4KBKURumOMimwMIyurUw==
#expiration: 1 day(86400s)
tuan.jwt.access-token-validity-in-seconds=86400
tuan.jwt.refresh-token-validity-in-seconds=86400
#
###
#config pagination
spring.data.web.pageable.one-indexed-parameters=true
###
#


###
#config upload file
###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB  

# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
###

