### GET request to example server
PUT localhost:8080/api/v1/jobs
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE3NjEyMjg2ODQsImlhdCI6MTc2MTE0MjI4NCwidXNlciI6eyJpZCI6OCwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IlR1YW4ifX0.XdNTu5JBHV5XJ1r3bbM5k5qgW_Wt7WEi6oPOllfjhnDKGarBmGpbyx0ZOi_karoPH5taM2ffN3bCrW8LI0SY9A
Content-Type: application/json

{
  "id": "1",
  "name": "Dev NodeJS Updated",
  "location":"Hà Nội",
  "salary": "10000000",
  "quantity": 10,
  "level": "JUNIOR",
  "description": "Ngầu",
  "startDate": "2025-11-11T13:55:58.454607Z",
  "endDate": "2026-11-11T13:55:58.454607Z",
  "active": true,
  "skills": [
    {
      "id": 1
    },
    {
      "id": 3
    },
    {
      "id": 7
    }
  ]

}

###