### GET request to example server
GET localhost:8080/api/v1/resumes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjpbIlJPTEVfVVNFUl9DUkVBVEUiLCJST0xFX1VTRVJfVVBEQVRFIl0sImV4cCI6MTc2MTY0Mzg0MSwiaWF0IjoxNzYxNTU3NDQxLCJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiSSdtIHN1cGVyIGFkbWluIn19.YWvX9xjc-XN_tCGCabHKGo23S3XbfKpJ9p4V5Z6Z0TiA0Y3rVFzz1ck6RvH23UFr9yTB1ceFoSeNVhjBiP-eQw

###