### GET request to example server
POST http://localhost:8080/api/v1/resumes/by-user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImV4cCI6MTc2MTU5MDk2NiwiaWF0IjoxNzYxNTA0NTY2LCJ1c2VyIjp7ImlkIjozLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwidXNlcm5hbWUiOiJUdeG6pW4gxJDhurlwIFRyYWkifX0.2UDdgzqS-D18CzS0ey9aCaVGQjAgNPkvUzKjpoAIUeZgk0es4bH8-6TimMfaOPXxg4HiNNPVRxGLVZJIOaQ7hA