### GET request to example server
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJIdXllbkBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjpbIlJPTEVfVVNFUl9DUkVBVEUiLCJST0xFX1VTRVJfVVBEQVRFIl0sImV4cCI6MTc2MTU5MDEwNiwiaWF0IjoxNzYxNTAzNzA2LCJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6Ikh1eWVuQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiSHV54buBbiB4aW5oIGfDoWkifX0.YOsf-_Mx77-tic26iEpUU2NhN-faYXWsEj5XxJi1-bawrksQJQxcxDGcNPRKg8mnWymNGsOGHMsbI4whpryD4w