### GET request to example server
POST localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE3NjEyMjg2ODQsImlhdCI6MTc2MTE0MjI4NCwidXNlciI6eyJpZCI6OCwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IlR1YW4ifX0.XdNTu5JBHV5XJ1r3bbM5k5qgW_Wt7WEi6oPOllfjhnDKGarBmGpbyx0ZOi_karoPH5taM2ffN3bCrW8LI0SY9A
Content-Type: application/json

{
  "name": "Nghiaaaaa",
  "email": "abc1@gmail.com",
  "password": "123456",
  "gender": "MALE",
  "address":"tphcm",
  "age": 26,
  "company": {
    "id": "9",
    "name": "jkljkl"
  }
}
###