### GET request to example server
DELETE localhost:8080/api/v1/users/12
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ0dWFuIjp7InByaW5jaXBhbCI6eyJwYXNzd29yZCI6bnVsbCwidXNlcm5hbWUiOiJIdXllbkBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6W3sicm9sZSI6IlJPTEVfVVNFUiJ9XSwiYWNjb3VudE5vbkV4cGlyZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWUsImNyZWRlbnRpYWxzTm9uRXhwaXJlZCI6dHJ1ZSwiZW5hYmxlZCI6dHJ1ZX0sImNyZWRlbnRpYWxzIjpudWxsLCJhdXRob3JpdGllcyI6W3sicm9sZSI6IlJPTEVfVVNFUiJ9XSwiZGV0YWlscyI6bnVsbCwiYXV0aGVudGljYXRlZCI6dHJ1ZX0sInN1YiI6Ikh1eWVuQGdtYWlsLmNvbSIsImV4cCI6MTc2MTAzNDk2NSwiaWF0IjoxNzYwOTQ4NTY1fQ.G_Pk0ctniYUdfkTEFwY5IEV2t4EK9GosXS89_yMuLZ2tR3ks88QJmmjT8qM79KmZNR-rYyNaueLmlxTOXjfufA
###