### GET request to example server
GET  localhost:8080/api/v1/users?page=1&size=10&sort=updatedAt,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJockBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjpbIlJPTEVfVVNFUl9DUkVBVEUiLCJST0xFX1VTRVJfVVBEQVRFIl0sImV4cCI6MTc2MTY1Njk1NywiaWF0IjoxNzYxNTcwNTU3LCJ1c2VyIjp7ImlkIjozLCJlbWFpbCI6ImhyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiSFIgVHVhbiJ9fQ.M2AHAsAOo2SlluEWuQQ8OUmzAOijOHGYzXc0p266QRwlZQ2JugN6EskqFnCyuEqzihgA9QafgDqLbnyr9EqbBQ
###