### GET request to example server
GET  localhost:8080/api/v1/users?page=1&size=10&sort=updatedAt,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjpbIlJPTEVfVVNFUl9DUkVBVEUiLCJST0xFX1VTRVJfVVBEQVRFIl0sImV4cCI6MTc2MTY0MjE0NywiaWF0IjoxNzYxNTU1NzQ3LCJ1c2VyIjp7ImlkIjoxLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiSSdtIHN1cGVyIGFkbWluIn19.RisH_if4UVsCm6isBxy1QoAn05ghqfhiJWNC1jX62gU11OnnEVuk5r8U9vYVMV9r1nrvWAjLbCvLOG3zTZIOng
###