### GET request to example server
GET localhost:8080/api/v1/users/10
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjpbIlJPTEVfVVNFUl9DUkVBVEUiLCJST0xFX1VTRVJfVVBEQVRFIl0sImV4cCI6MTc2MTQ5NzQzMiwiaWF0IjoxNzYxNDExMDMyLCJ1c2VyIjp7ImlkIjo4LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiVHVhbiJ9fQ.lwXIefgnxfBP-EfdE1mr0BPlr3URXVlgpauSVVmZWuetU06rS7bz7cjnVXME9mOvXQSoqyIt2hkFhMUTtd7HWQ
###